/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CoursesCourseIdRouteImport } from './routes/courses.$courseId'
import { Route as BlogChapterIdLessonSlugRouteImport } from './routes/blog.$chapterId.$lessonSlug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const CoursesCourseIdRoute = CoursesCourseIdRouteImport.update({
  id: '/$courseId',
  path: '/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const BlogChapterIdLessonSlugRoute = BlogChapterIdLessonSlugRouteImport.update({
  id: '/$chapterId/$lessonSlug',
  path: '/$chapterId/$lessonSlug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/blog/$chapterId/$lessonSlug': typeof BlogChapterIdLessonSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/blog': typeof BlogIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/blog/$chapterId/$lessonSlug': typeof BlogChapterIdLessonSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/courses': typeof CoursesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/courses/$courseId': typeof CoursesCourseIdRoute
  '/blog/': typeof BlogIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/blog/$chapterId/$lessonSlug': typeof BlogChapterIdLessonSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/courses'
    | '/sitemap.xml'
    | '/courses/$courseId'
    | '/blog/'
    | '/courses/'
    | '/blog/$chapterId/$lessonSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/courses/$courseId'
    | '/blog'
    | '/courses'
    | '/blog/$chapterId/$lessonSlug'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/courses'
    | '/sitemap.xml'
    | '/courses/$courseId'
    | '/blog/'
    | '/courses/'
    | '/blog/$chapterId/$lessonSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  CoursesRoute: typeof CoursesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/courses/$courseId': {
      id: '/courses/$courseId'
      path: '/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof CoursesCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/blog/$chapterId/$lessonSlug': {
      id: '/blog/$chapterId/$lessonSlug'
      path: '/$chapterId/$lessonSlug'
      fullPath: '/blog/$chapterId/$lessonSlug'
      preLoaderRoute: typeof BlogChapterIdLessonSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogIndexRoute: typeof BlogIndexRoute
  BlogChapterIdLessonSlugRoute: typeof BlogChapterIdLessonSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogIndexRoute: BlogIndexRoute,
  BlogChapterIdLessonSlugRoute: BlogChapterIdLessonSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CoursesRouteChildren {
  CoursesCourseIdRoute: typeof CoursesCourseIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesCourseIdRoute: CoursesCourseIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  CoursesRoute: CoursesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
